apiVersion: v1
kind: Secret
metadata:
  name: glpi-secret
type: Opaque
data:
  db_user: {{ .Values.mariadb.user | b64enc | quote }}
  db_password: {{ .Values.mariadb.password | b64enc | quote }}
  db_root_password: {{ .Values.mariadb.rootPassword | b64enc | quote }}
